run:
  experiment_name: "visual_cifar10_effi"
  output_dir: "runs"
  seed: 42
  device: "auto"
  cudnn:
    benchmark: false
    deterministic: true

data:
  name: "cifar10"
  num_samples: 50000
  batch_size: 128
  num_workers: 4
  cfg:
    cifar10:
      root: "./data"
      download: true
      class_conditional: true
      cf_guidance_p: 0.0
      img_size: 224 # Default size for pretrained resnet model

model:
  name: "efficientnet_b1"
  common:
    num_classes: 10
    pretrained: false

train:
  epochs: 100
  lr: 2.0e-4
  weight_decay: 0.0
  grad_clip: 1.0
  log_interval: 50
  ckpt_interval: 10
  sample_interval: 1
  sample_size: 64
  checkpoint_dir: "runs/checkpoints"   # where to save
  save_every_steps: 1000               # autosave cadence
  keep_last_k: 3                       # how many checkpoints to retain
  resume_from: "latest"                # "", path/to/ckpt.pt, or "latest"
  save_best_on: "val_acc"             # (TODO) metric name in your eval dict
  save_rng_state: true                 # restore RNG for exact reproducibility
  warmup: 5000

# Tracking & Logging
tracking:
  tensorboard: true
  mlflow:
    enabled: false
    tracking_uri: "file:./mlruns"
    experiment_name: "effi_cifar10"